version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Pas5w0rd*

volumes:
  postgres_db:
